### ISSUE TITLE
Still doing this?

### ISSUE THREAD

**Issue by GollyJer** [barrcodes/visual-studio-mac-settings#1]
Hey! I'm curious if you're still managing this with recent version of vscode and their keyboard.json file.

**Comment by barrcodes** [comment]
Ha! Sorry, I just noticed this. I haven't touched this in years, and I think there was a point I even started embracing the vanilla mac hotkeys. I use windows primarily again.

I know this was 2 years ago, just felt bad that I hadn't replied.
